create communication for marked as resolved
uwcirg/isacc-messaging-client-sof pull request #99
Opened 2024-11-27 23:35 UTC by achen2401

part of story https://www.pivotaltracker.com/story/show/188624366

- create a new communication when a messaged is marked as read.
Example communication posted:
```
{
        "resourceType": "Communication",
        "id": "2604598",
        "meta": {
          "versionId": "1",
          "lastUpdated": "2024-11-27T18:28:56.642-05:00"
        },
        "partOf": [
          {
            "reference": "CarePlan/2596233"
          }
        ],
        "status": "completed",
        "category": [
          {
            "coding": [
              {
                "system": "https://isacc.app/CodeSystem/communication-type",
                "code": "isacc-message-resolved-no-send"
              }
            ]
          }
        ],
        "subject": {
          "reference": "Patient/2cda5aad-e409-4070-9a15-e1c35c46ed5a"
        },
        "sent": "2024-11-27T23:28:56.345Z",
        "payload": [
          {
            "contentString": "Marked as read"
          }
        ],
        "note": [
          {
            "text": "marked as read, staff-entered"
          }
        ]
      }
```

Will be displayed on the UI in the messages panel as such:
![Screenshot 2024-11-27 at 3 32 27 PM](https://github.com/user-attachments/assets/19a4eb10-0ca0-4e49-b679-283721e3dc2f)

2024-11-27 23:46 UTC, pbugni approved these changes
nice work.

2024-12-02 01:52 UTC, mcjustin commented
Thanks for addressing this promptly @achen2401 ! Can you please share a screenshot of what a "marked as read" action looks like in the messaging client history UI alongside the message that has been marked as read? I could see this handled a few different ways in the UI...

2024-12-02 06:26 UTC, achen2401 commented
> Can you please share a screenshot of what a "marked as read" action looks like in the messaging client history UI alongside the message that has been marked as read? I could see this handled a few different ways in the UI...

@mcjustin here is the screenshot
![IMG_0110](https://github.com/user-attachments/assets/779e22c1-49f6-4b72-a790-4f198b205206)

2024-12-02 18:47 UTC, mcjustin requested changes

2024-12-02 18:47 UTC, mcjustin commented on src/components/MessagingView.tsx
> +        content: "Marked as read",
Change to "Prior message(s) marked as read"

2024-12-02 18:47 UTC, mcjustin commented on src/components/MessagingView.tsx
> +        content: "Marked as read",
Thanks @achen2401  What I'm getting snagged on is the case where there may be multiple unread messages from a recipient. I'd prefer to change this new "Marked as read" message to "Prior message(s) marked as read". 

I'd like us to also change the "MARK MESSAGE AS READ/RESOLVED" button to "MARK MESSAGE(S) AS READ/RESOLVED" and in the text above it, "Un-responded message" to "Un-responded message(s)" since the button can effectively apply to multiple messages - my aim is to clarify that this action isn't tied to an individual message per se, but more a state of the recipient.

Thoughts?

![image](https://github.com/user-attachments/assets/e6001cc1-728a-4e3a-94bc-3a82afbe0c68)

2024-12-02 18:52 UTC, achen2401 commented on src/components/MessagingView.tsx
> +        content: "Marked as read",
thank you @mcjustin  the changes sound good.  I will make the changes and comment here when I am done.

2024-12-02 19:26 UTC, achen2401 commented on src/components/MessagingView.tsx
> +        content: "Marked as read",
@mcjustin the fixes are made. I updated the PR with screenshots of the changes (I grabbed the screenshots for Eleven Upside-down in the [shared dev instance](https://femr.isacc.dev.cirg.uw.edu/) if you want to see the actual example).  Let me know if any more change is needed?

2024-12-02 19:34 UTC, mcjustin approved these changes

2024-12-02 23:23 UTC, merged